appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c32ce7b87b5930700c33961
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: mOeRtG+VXIpGFURl2hkzXRIZAS+jk4zVR4xr7R4/ELTswCOnli+PbcHjk42FUarJVkMErePLuANPPjuQpAiribWvTRKKUq9NeC/hiVx0VDPmlmVj/Fu/s5RhGUl3Wy7OaPoNQRbAfjZvYlM99zEmZfCjL0W2mKNmXwIni+u3RSUX+GBm4Z961VArce0yH+5E02uTXyLvQOQpbcWYt6uImR3+S7TtOsBPQVXOtECXRhk5W5RocQNCRg0TP0qjr3c1xiBqLw0BkjC1ANXnZ138evrF9XENFK2wSzGm4TdAtmNgclbsxdD4vOjd5DQQBkfHOdial66lOfGp/3NmOcfLoP9eZW1+YcWdUa9SLD1Bozc68+qYULkHzBz3SNk28fxe5biOGmqn2/GGLkXZ118OYtMLAp01rcqXGjXi3qz45VWkUTuzadqUG4F2D4bjiiAQ0tTx+Ff4WixteY3F25POYsObnCI1firURYhFqWQdWTRgrZp99vnVTyJQDN6kRxVFDoOEhijUsGnYPb/Awm6FbDFZ/R5UMW+kXyaG6Oa7eDR4ycWkCtjPi4Ss4XicYWcTaIPgB8SHRrSK4sZlbGFYwk2nwzeMJok+IMco6J2pEpCMRcDcJZeNSkZvZQTDi/peG5aFJZfOhaPJJ97uaVGl+JNbwu5ajc7sJly4bha2O18=}
